### OOP ###

In [1]:
class PlayerCharacter:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def run(self):
        print('run')
        return 'done'

    
    
player1 = PlayerCharacter('Adyaan', 30)
player2 = PlayerCharacter('Kavya', 29)
player2.attack = 50
player1.sleep = 9

print(player1.name)
print(player1.age)
print(player2.attack)
print(player1.sleep)


Adyaan
30
50
9


In [2]:
class PlayerCharacter:
    membership = True   # Class Object Attribute
    def __init__(self, name, age):
        if (self.membership):
            self.name = name # attribute
            self.age = age
        
    def shout(self):
        print(f'my name is {self.name}')
        #return 'done'
        
    @classmethod
    def adding_things(cls, num1, num2):
        return num1 + num2
    
    @staticmethod
    def adding_things2(num1, num2):
        return num1 + num2
    
    
player1 = PlayerCharacter('Adyaan', 30)
player2 = PlayerCharacter('Kavya', 29)
print(player2.name)
print(player1.membership)
print(player1.shout())
print(player1.adding_things(5,8))
print(player2.adding_things2(5,8))


Kavya
True
my name is Adyaan
None
13
13


In [3]:
# @classmethods

In [4]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)



class Person():
  def __init__(self, name , age, notes):
    self.name = name
    self.age = age
    self.notes = notes
  
  def __iter__(self):
    yield self
    yield self.name
    yield self.age
    yield self.notes

  def hello(self):
    return(f"Hello! I am {self.name}, {self.notes}")

  def __str__(self):
    return "Person: " + self.name

  @classmethod
  def columns(cls):
    return['items', 'name', 'age', 'notes']

class Struct:
  def __init__(self):
    self.facet = {}

  def add_to_facet(self, item):
    self.facet[item.name] = item

  @property
  def items(self):
    return pd.DataFrame(list(self.facet.values()), columns=Person.columns())

people = Struct()
print(people)

people = Struct()
people.add_to_facet(Person('Jim', 42, 'The time has come for all good men to come to the aid of the party'))
people.add_to_facet(Person('Jane', 24, 'She sells sea shells on the sea shore'))
people.add_to_facet(Person('Jill', 17, 'The quick brown fox jumps over the lazy dog'))
print(people.items)    


[[1 2 3]
 [4 5 6]
 [7 8 9]]


NameError: name 'pd' is not defined

### __init__ 

In [ ]:

class PlayerCharacter:
    def __init__(self, name='anonymous', age=0):
        if (age >= 18):
            self.name = name
            self.age = age
        
    def run(self):
        print(f'My name is {self.name} and I am {self.age} year old')
  
    
    
player1 = PlayerCharacter('Adyaan', 18)
print(player1.run())

# print(player1.name)
# print(player1.age)


### Exercise: Cats Everywhere



In [ ]:
class cat:
    #species = 'mammal'
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
# Instantiate the Cat object with 3 cats

peanut = cat('Peanut', 3)
garfield = cat('Garfield', 5)
snickers = cat('snickers', 1)

# Find the oldest cat

def get_oldest_cat(*args):
    return max(args)


#Output

print(f'The oldest cat is {get_oldest_cat(peanut.age, garfield.age, snickers.age)} year old')


## @classmethod and @staticmethod

In [ ]:
class PlayerCharacter:
    
    membership = True
    def __init__(self, name, age):
      
        self.name = name
        self.age = age

    def shout(self):
        print(f'My name is {self.name} and I am {self.age} year old')
  
    
    @classmethod
    def adding_things(cls, num1, num2):
        return num1 + num2
    
    
player1 = PlayerCharacter('Adyaan', 18)
print(player1.adding_things(2,5))

print(player1.name)
print(player1.age)


In [ ]:
class PlayerCharacter:
    
    membership = True
    def __init__(self, name, age):
      
        self.name = name
        self.age = age

    def shout(self):
        print(f'My name is {self.name} and I am {self.age} year old')
  
    
    @classmethod
    def adding_things(cls, num1, num2):
        return cls('Adyaan', num1 + num2)
    
    
    
player1 = PlayerCharacter('Adyaan', 18)
Player3=PlayerCharacter.adding_things(2,5)
print(Player3.age)


In [ ]:
class PlayerCharacter:
    
    membership = True
    def __init__(self, name, age):
      
        self.name = name
        self.age = age

    def shout(self):
        print(f'My name is {self.name} and I am {self.age} year old')
  
    
    @classmethod
    def adding_things(cls, num1, num2):
        return cls('Adyaan', num1 + num2)
    
    
    @staticmethod
    def adding_things2(num1, num2):
        return num1 + num2
    
    
#player1 = PlayerCharacter('Adyaan', 18)
Player3=PlayerCharacter.adding_things2(3,5)
print(Player3.age)


## 4 Pillars of OOP

### 1st Pillar:- Encapsulation

In [ ]:
class PlayerCharacter:
     
    def __init__(self, name, age):
        self.name = name
        self.age = age
        

    def speak(self):
        print(f'My name is {self.name} and I am {self.age} years old')
  
    
    
    
player1 = PlayerCharacter('Adyaan', 300)
player1.speak()

### 2nd pillar:- Abstraction

This is not a good way to work becouse it is rename the functions

In [ ]:
class PlayerCharacter:
     
    def __init__(self, name, age):
        self.name = name
        self.age = age
        

    def speak(self):
        print(f'My name is {self.name} and I am {self.age} years old')
  
    
    
    
player1 = PlayerCharacter('Adyaan', 300)
player1.name = 'oooooheeeeeeeee'
player1.speak = 'hoooooooooo'

print(player1.speak)
print(player1.name)


### Private vs Public Variables

When we use _ after self then it have been private e.g. _name, _age. This means you can not modify it

In [ ]:
class PlayerCharacter:
     
    def __init__(self, name, age):
        self._name = name
        self._age = age
        

    def speak(self):
        print(f'My name is {self._name} and I am {self._age} years old')
  
    
    
    
player1 = PlayerCharacter('Adyaan', 300)
print(player1.speak())


### 3rd Pillar :- Inheritance

In [ ]:
class User():
    def sing_in(self):
        print('logged in')
        
class Wizard(User):
    def __init__(self, name, power):
        self.name = name
        self.power = power
        
    def attack(self):
        print(f'Attacking with power of {self.power}')
    

class Archer(User):
    def __init__(self, name, num_arrows):
        self.name = name
        self.num_arrows = num_arrows
        
    def attack(self):
        print(f'Attacking with arrows:  arrows left - {self.num_arrows}')
         
        
    
    
Wizard1 = Wizard('Adyaan', 100)
archer1 = Archer('Kavya', 100)

# print(Wizard1.name)
# Wizard1.power
Wizard1.attack()
Wizard1.sing_in()
archer1.attack()
archer1.sing_in()


In [ ]:
class User():
    def sing_in(self):
        print('logged in')
        
class Wizard(User):
    def __init__(self, name, power):
        self.name = name
        self.power = power
        
    def attack(self):
        print(f'Attacking with power of {self.power}')
    

class Archer(User):
    def __init__(self, name, num_arrows):
        self.name = name
        self.num_arrows = num_arrows
        
    def attack(self):
        print(f'Attacking with arrows:  arrows left - {self.num_arrows}')
         
        
    
    
Wizard1 = Wizard('Adyaan', 100)
archer1 = Archer('Kavya', 100)

print(isinstance(Wizard1, object))


### 4th Pillar:- Polymorphism

In [ ]:
class User():
    def sing_in(self):
        print('logged in')
        
class Wizard(User):
    def __init__(self, name, power):
        self.name = name
        self.power = power
        
    def attack(self):
        
        print(f'Attacking with power of {self.power}')
    

class Archer(User):
    def __init__(self, name, num_arrows):
        self.name = name
        self.num_arrows = num_arrows
        
    def attack(self):
        print(f'Attacking with arrows:  arrows left - {self.num_arrows}')
         
        
    
    
Wizard1 = Wizard('Adyaan', 100)
archer1 = Archer('Kavya', 100)

def player_attack(char):
    char.attack()
    
player_attack(Wizard1)
player_attack(archer1)

print()

for char in [Wizard1, archer1]:
    char.attack()


### Exercies Extending list

In [20]:
class Pets():
    
    
    animals =  []    
    def __init(self, animals):
        self.animals = animals
        
    def walk(self):
        for animal in self.animals:
            print(animal.walk())
                        
class Cat():
    is_lazy = True

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def walk(self):
        return f'{self.name} is just walking around'

class Simon(Cat):

    def sing(self, sounds):
        return f'{sounds}'

class Sally(Cat):
    def sing(self, sounds):
        return f'{sounds}'

class Chinky(Cat):
    def sing(self, sounds):
        return f'sounds'

# 1) Add another Cat    
        
class Minky(Cat):
    def sing(self, sounds):
        return f'sounds'
    
    
#2) creating a list of all of the pets (creating 4 cats instances from the above)

My_cats = [Simon('Simon', 4), Sally('Sally', 10), Chinky('Chinky', 1), Minky('Minky',12)]


#3) Instantiate the Pet class with all your cats
my_pets = Pets(My_cats)
#my_pets = Pets(my_cats)
# 4) Output all of the cats singing using the my pets instance
print(my_cats.walk())          
        
            
        

TypeError: Pets() takes no arguments

## Supper

In [ ]:
class User(object):
    def __init__(self, email):
        self.email = email
        
    
    def sing_in(self):
        print('logged in')
        
class Wizard(User):
    def __init__(self, name, power, email):
        User.__init__(self, email)
        self.name = name
        self.power = power
        
    def attack(self):
        
        print(f'Attacking with power of {self.power}')
    

class Archer(User):
    def __init__(self, name, num_arrows, email):
        super().__init__(email)
        self.name = name
        self.num_arrows = num_arrows
        
    def attack(self):
        print(f'Attacking with arrows:  arrows left - {self.num_arrows}')
         
        
    
    
Wizard1 = Wizard('Adyaan', 100, 'adyaan.singh@gmail.com')
archer1 = Archer('Kavya', 100, 'kavya.singh@gmail.com')

print(Wizard1.email)
archer1.email

In [ ]:
# Object Introspections

class User(object):
    def __init__(self, email):
        self.email = email
        
    
    def sing_in(self):
        print('logged in')
        
class Wizard(User):
    def __init__(self, name, power, email):
        User.__init__(self, email)
        self.name = name
        self.power = power
        
    def attack(self):
        
        print(f'Attacking with power of {self.power}')
    

class Archer(User):
    def __init__(self, name, num_arrows, email):
        super().__init__(email)
        self.name = name
        self.num_arrows = num_arrows
        
    def attack(self):
        print(f'Attacking with arrows:  arrows left - {self.num_arrows}')
         
        
    
#Intropections (dir)   

Wizard1 = Wizard('Adyaan', 100, 'adyaan.singh@gmail.com')
archer1 = Archer('Kavya', 100, 'kavya.singh@gmail.com')

print(dir(Wizard1))
#archer1.email

In [ ]:
### Dunder Methods

class Toy():
    def __init__(self, color, age):
        self.color = color
        self.age = age

    def __str__(self):
        return f'{self.color}'
        
action_figure = Toy('Red', 10)
    
print(str(action_figure))        

### MRO - Method Resolution Order


In [15]:
class A:
    num = 20
    
    
class B(A):
    pass

class C(A):
    num = 1
    
class D(B,C):
    pass

D.__mro__

(__main__.D, __main__.B, __main__.C, __main__.A, object)